title:             airChen 的博客
email:             renzhichen2016@gmail.com
description:       读书以训诂为本,诗文以声调为本
author:            airChen
baseurl:     "/"
url:         "https://airchen.github.io"

# Social Profiles
github_username:   AirChen

# Build settings
markdown:          kramdown
markdown_ext:  markdown,mkd,mkdn,md
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

theme: jekyll-theme-cayman