title:             AirChen's Blog
email:             renzhichen2012@163.com
description:       ...
author:            AirChen
baseurl:     "/Blogs"
url:         "https://airchen.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   AirChen
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
markdown_ext:  markdown,mkd,mkdn,md
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
